version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloudmitigator-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./backend/data/ttp_mappings.json:/data/ttp_mappings.json
    networks:
      - cloudmitigator-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloudmitigator-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    networks:
      - cloudmitigator-network
    restart: unless-stopped

networks:
  cloudmitigator-network:
    driver: bridge
